[package]
authors = ["Marcel Müller <neikos@neikos.email>"]
name = "rustbreak"
version = "0.2.1"
description = "A single file database"
documentation = "http://neikos.me/rustbreak/rustbreak/index.html"
homepage = "https://github.com/TheNeikos/rustbreak"
repository = "https://github.com/TheNeikos/rustbreak"
readme = "README.md"
license = "MPL-2.0"
keywords = ["database", "simple", "fast", "daybreak", "rustbreak"]

[dependencies]
bincode = "0.6.0"
fs2 = "0.2.5"
quick-error = "1.1.0"
serde = "0.8.12"

[dev-dependencies]
tempfile = "2.1"
